version: '3.8'
services:

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: waham
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"   
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  waha:
    image: devlikeapro/waha   
    restart: unless-stopped
    environment:
      WHATSAPP_API_KEY: ${WAHA_API_KEY:-testkey}
      WHATSAPP_API_WEBHOOK_SECRET: ${WAHA_WEBHOOK_SECRET:-testwebhook}
      WAHA_DASHBOARD_USER: admin
      WAHA_DASHBOARD_PASS: admin
      
    ports:
      - "9998:3000"

    depends_on:
      - db

  api:
    build: .
    restart: unless-stopped

    env_file:
      - .env.docker

    
    ports:
      - "3000:3000"
    depends_on:
      - db
      - waha
    volumes:
      - .:/usr/src/app   
    command: npm run start:dev   

volumes:
  db-data:
